/**
 * Crown Money Export Module
 * CSV and PDF export with branding
 */
const CrownExport = (() => {

  function downloadBlob(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  // Export data as CSV
  function toCSV(title, headers, rows) {
    const escape = (val) => {
      const s = String(val === null || val === undefined ? '' : val);
      return s.includes(',') || s.includes('"') || s.includes('\n')
        ? '"' + s.replace(/"/g, '""') + '"'
        : s;
    };

    let csv = `Crown Money Financial Toolkit - ${title}\n`;
    csv += `Generated: ${new Date().toLocaleDateString('en-AU')}\n\n`;
    csv += headers.map(escape).join(',') + '\n';
    rows.forEach(row => {
      csv += row.map(escape).join(',') + '\n';
    });
    csv += `\nBrought to you by CrownMoney.com.au`;

    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    downloadBlob(blob, `CrownMoney_${title.replace(/\s+/g, '_')}_${Date.now()}.csv`);
  }

  // Export data as PDF
  function toPDF(title, headers, rows, chartCanvasId = null) {
    if (typeof jspdf === 'undefined' || !jspdf.jsPDF) {
      alert('PDF export library not loaded. Please try again.');
      return;
    }

    const { jsPDF } = jspdf;
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header bar
    doc.setFillColor(26, 26, 46);
    doc.rect(0, 0, pageWidth, 28, 'F');

    // Gold crown text
    doc.setTextColor(226, 176, 58);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Crown Money', 14, 14);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Financial Toolkit', 14, 22);

    // Title
    doc.setTextColor(26, 26, 46);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 14, 40);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120, 120, 140);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-AU')}`, 14, 47);

    let startY = 54;

    // Chart image
    if (chartCanvasId) {
      const canvas = document.getElementById(chartCanvasId);
      if (canvas) {
        try {
          const imgData = canvas.toDataURL('image/png');
          const imgWidth = pageWidth - 28;
          const imgHeight = (canvas.height / canvas.width) * imgWidth;
          doc.addImage(imgData, 'PNG', 14, startY, imgWidth, Math.min(imgHeight, 80));
          startY += Math.min(imgHeight, 80) + 8;
        } catch (e) {
          // chart capture failed, skip
        }
      }
    }

    // Table
    if (headers && rows && rows.length > 0) {
      doc.autoTable({
        head: [headers],
        body: rows,
        startY: startY,
        theme: 'grid',
        headStyles: {
          fillColor: [26, 26, 46],
          textColor: [226, 176, 58],
          fontSize: 8,
          fontStyle: 'bold'
        },
        bodyStyles: {
          fontSize: 8,
          textColor: [50, 50, 60]
        },
        alternateRowStyles: {
          fillColor: [248, 249, 250]
        },
        margin: { left: 14, right: 14 },
        styles: { cellPadding: 3 }
      });
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      const pageH = doc.internal.pageSize.getHeight();
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 170);
      doc.text(
        'This report is brought to you by CrownMoney.com.au — helping hardworking Australians pay off their home loan sooner.',
        pageWidth / 2, pageH - 10, { align: 'center' }
      );
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageH - 10, { align: 'right' });
    }

    doc.save(`CrownMoney_${title.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
  }

  // Share via Web Share API or copy link
  async function share(title, text) {
    if (navigator.share) {
      try {
        await navigator.share({ title: `Crown Money - ${title}`, text, url: 'https://crownmoney.com.au' });
      } catch (e) {
        // user cancelled
      }
    } else {
      try {
        await navigator.clipboard.writeText(text + '\n\nGenerated by CrownMoney.com.au');
        alert('Summary copied to clipboard!');
      } catch (e) {
        alert('Unable to share. Please copy the results manually.');
      }
    }
  }

  return { toCSV, toPDF, share };
})();
